### PR TITLE
Convert project to TypeScript

### PR DESCRIPTION
**Pull request by lhjt**
# Summary

This PR: 
- [x] Converts the project to use TypeScript instead of Javascript. 
- [x] Adds a prettier configuration file to standardise formatting.

### Any changes to the API?

There are no changes to the API. End users will still consume the package in the same way.

### What did you change?

The `typings` directory no longer exists as all typings have been moved to the TypeScript files themselves. The TS compiler automatically generates when building and publishing to NPM.

### CODE REVIEW

**Comment by lhjt** [comment]
I've tested this package locally and update the tests to work with this new setup.

@MatteZ02 would you want the code that checks for appropriate types to be removed or maintained? e.g. :
https://github.com/MatteZ02/discord-interactions/blob/08802e3ef429e9b960679667bfeca656e823f9a7/src/core/InteractionsClient.js#L58-L68

**Comment by lhjt** [comment]
I've tested this package locally and update the tests to work with this new setup.

@MatteZ02 would you want the code that checks for appropriate types to be removed or maintained? e.g. :
https://github.com/MatteZ02/discord-interactions/blob/08802e3ef429e9b960679667bfeca656e823f9a7/src/core/InteractionsClient.js#L58-L68

**Comment by MatteZ02** [comment]
imop that code can be maintained. Tho do share your opinion if you've got one.

**Comment by lhjt** [comment]
That sounds fine to me. It will catch cases where end users do not have linting available.

**Review by MatteZ02 — COMMENTED** [review]
Ill just have to run the tests myself before merging. So far seems all good tho.

**Comment by Nicholaiii** [comment]
In my opinion it's worth looking into using a validation library like [fastest-validator](https://github.com/icebob/fastest-validator) or [joi](https://github.com/sideway/joi) 
It's more maintainable and expressive, and has less repetition.

**Comment by lhjt** [comment]
I second this. However, I believe that it would be more appropriate to include that in a separate PR as this primarily focuses on migrating the project to TS.

**Comment by Nicholaiii** [comment]
> 
> 
> I second this. However, I believe that it would be more appropriate to include that in a separate PR as this primarily focuses on migrating the project to TS.

Absolutely agreed, I just caught the topic and thought I'd chime in

**Pull request merged**
